filename: "res_evt"
modelname: "res_evt"
root_data_folder: "data"
root_model_folder: "models"
# class_labels: ["sink_cold", "sink_hot", "toilet", "shower"]
# class_labels: ["sink_cold", "sink_hot", "toilet", "shower"]
class_labels: ["toilet", "sink"]
# filter_labels: ["toaleta", "chiuveta_rece", "chiuveta_calda", "dus"]
# filter_labels: ["toaleta","chiuveta_rece_baie","chiuveta_calda_baie","chiuveta_rece_bucatarie","chiuveta_calda_bucatarie","dus"]
filter_labels: ["toaleta", "chiuveta_rece", "chiuveta_calda"]
apply_balancing: True

map_labels: {
  "chiuveta": 10,
  "chiuveta_rece": 1,
  "chiuveta_calda": 1,
  "chiuveta_rece_baie": 11,
  "chiuveta_calda_baie": 12,
  "chiuveta_rece_bucatarie": 13,
  "chiuveta_calda_bucatarie": 14,
  "toaleta": 3,
  "dus": 4,
  "masina_spalat": 5,
  "masina_spalat_vase": 6
}

train_percent: 80
activation_fn: "softmax"
loss_fn: "categorical_crossentropy"
run_clean: False
# model_to_eval: "./models/res_evt_dense_3_top.h5"
# model_to_eval: "./models/res_evt_rnn_5_top.h5"
model_to_eval: "./models/res_evt_1.skl"
use_normalization: True
