filename: "res_evt"
modelname: "res_evt_1"
root_data_folder: "data"
root_model_folder: "models"
root_model_container: "models/m1"
class_labels: ["sink_cold", "sink_hot", "toilet", "shower"]
# class_labels: ["sink", "toilet", "shower"]
filter_labels1: ["toaleta", "chiuveta_rece", "chiuveta_calda", "dus"]
filter_labels: [
  "toaleta",
  "chiuveta_rece_baie",
  "chiuveta_calda_baie",
  "chiuveta_rece_bucatarie",
  "chiuveta_calda_bucatarie",
  "dus"
]
map_labels0: {
  "chiuveta_rece": 1,
  "chiuveta_calda": 2,
  "toaleta": 3,
  "dus": 4,
  "masina_spalat": 5,
  "masina_spalat_vase": 6
}
map_labels1: {
  "chiuveta_rece_baie": 1,
  "chiuveta_calda_baie": 2,
  "chiuveta_rece_bucatarie": 3,
  "chiuveta_calda_bucatarie": 4,
  "toaleta": 5,
  "dus": 6,
  "masina_spalat": 7,
  "masina_spalat_vase": 8
}
map_labels: {
  "chiuveta_rece_baie": 1,
  "chiuveta_calda_baie": 2,
  "chiuveta_rece_bucatarie": 1,
  "chiuveta_calda_bucatarie": 2,
  "toaleta": 5,
  "dus": 6,
  "masina_spalat": 7,
  "masina_spalat_vase": 8
}
load_from_container: True
one_hot_encoding: False
train_percent: 80
activation_fn: "softmax"
loss_fn: "categorical_crossentropy"
run_clean: False
model_to_eval: "./models/res_evt_1_rnn_5.h5"
model_to_eval1: "./models/res_evt_1_2.skl"
use_normalization: False
