filename: "res_evt"
modelname: "res_evt_1"
root_data_folder: "data"
root_model_folder: "models"
root_model_container: "models/m1"
filter_labels1: ["toaleta", "chiuveta_rece", "chiuveta_calda", "dus"]
filter_labels: ["toaleta", "chiuveta_rece_baie", "chiuveta_calda_baie", "chiuveta_rece_bucatarie", "chiuveta_calda_bucatarie", "dus"]
load_from_container: True
one_hot_encoding: False
train_percent: 80
activation_fn: "softmax"
loss_fn: "categorical_crossentropy"
run_clean: False
model_to_eval: "./models/res_evt_1_dense_1.h5"
use_normalization: True
